
#generated by https://curlconverter.com/#r
  
  require(httr)

headers = c(
  `User-Agent` = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0',
  `Accept` = '*/*',
  `Accept-Language` = 'de,en-US;q=0.7,en;q=0.3',
  `Accept-Encoding` = 'gzip, deflate',
  `Referer` = 'https://www.facebook.com/',
  `Content-type` = 'application/x-www-form-urlencoded',
  `Origin` = 'https://www.facebook.com',
  `Connection` = 'keep-alive',
  `Sec-Fetch-Dest` = 'empty',
  `Sec-Fetch-Mode` = 'cors',
  `Sec-Fetch-Site` = 'same-site',
  `Pragma` = 'no-cache',
  `Cache-Control` = 'no-cache',
  `TE` = 'trailers'
)

params = list(
  `_app` = 'ADS_MANAGER',
  `_reqName` = 'adaccount/delivery_estimate',
  `access_token` = 'EAABsbCS1iHgBAEzsITA5Ttg5C7A94ZCmtZCOrxi4OLee6j1DeQqYwsWZCBgvZBBkp4Y3zPbf3GPDzZCsFYa7ktX9CoQtUY5hsvjy0pfMQhly9ZAyTMexIPl831AJPReVgApmJwYNSHymYq1pRO8HKTsqcUZAoiuphGW85auursfwAZDZD',
  `method` = 'get',
  `qpl_active_flow_ids` = '270213183',
  `qpl_active_flow_instance_ids` = '270213183_b7f2a4eaf93b38d76',
  `__cppo` = '1'
)

data = list(
  `__activeScenarioIDs` = '["f1d72463db28672_1645617531133","f21374688903106_1645617531135"]',
  `__activeScenarios` = '["am:edit_targeting:audience_estimates","save_changes"]',
  `_app` = 'ADS_MANAGER',
  `_reqName` = 'adaccount/delivery_estimate',
  `_reqSrc` = 'AdsDeliveryEstimateDataLoader',
  `_sessionID` = '7c9a88b4d5cc6fb7',
  `attribution_spec` = '[{"event_type":"CLICK_THROUGH","window_days":1}]',
  `bid_strategy` = 'LOWEST_COST_WITHOUT_CAP',
  `budget_guardrail` = 'false',
  `currency` = 'EUR',
  `include_headers` = 'false',
  `is_cbo_enabled` = 'false',
  `locale` = 'en_US',
  `method` = 'get',
  `optimization_goal` = 'LINK_CLICKS',
  `prediction_duration` = '0',
  `pretty` = '0',
  `qpl_active_flow_ids` = '270213183',
  `qpl_active_flow_instance_ids` = '270213183_b7f2a4eaf93b38d76',
  `send_long_term_prediction_shadow_request` = 'true',
  `skip_bid_suggestion` = 'true',
  `suppress_http_code` = '1',
  `targeting_as_signal` = '0',
  `targeting_spec` = '{"geo_locations":{"countries":["ES"],"location_types":["home"]},"age_min":18,"age_max":65,"publisher_platforms":["facebook","instagram","audience_network","messenger"],"facebook_positions":["feed","instant_article","instream_video","right_hand_column","video_feeds","marketplace","story","facebook_reels_overlay","search","groups_feed"],"instagram_positions":["stream","story","explore","reels","shop"],"messenger_positions":["messenger_home","story"],"device_platforms":["mobile","desktop"],"audience_network_positions":["classic","rewarded_video"],"oculus_positions":[],"excluded_publisher_list_ids":[],"user_device":[],"excluded_user_device":[],"user_os":[],"wireless_carrier":[],"targeting_optimization":"none","exclusions":{"behaviors":[{"id":"6086568164383","name":"Marketing API developers (last 90 days)"},{"id":"6063136545383","name":"Android: 360 degree media supported"}]},"flexible_spec":[{"life_events":[{"id":"6003053984972","name":"Long-distance relationship"}]}],"brand_safety_content_filter_levels":["FACEBOOK_STANDARD","AN_STANDARD"],"excluded_brand_safety_content_types":[]}',
  `xref` = 'f16a0811580a282'
)

res <- httr::POST(url = 'https://graph.facebook.com/v12.0/act_660797563979760/delivery_estimate', httr::add_headers(.headers=headers), query = params, body = data, encode = "form")

res

res$status_code
res$content

content(res,as="text")
reply <-content(res,as="parsed")
#now inspect the reply in the RStudio GUI
#find out how to extract the audience estimate:



#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
res <- httr::POST(url = 'https://graph.facebook.com/v12.0/act_660797563979760/delivery_estimate?_app=ADS_MANAGER&_reqName=adaccount%2Fdelivery_estimate&access_token=EAABsbCS1iHgBAEzsITA5Ttg5C7A94ZCmtZCOrxi4OLee6j1DeQqYwsWZCBgvZBBkp4Y3zPbf3GPDzZCsFYa7ktX9CoQtUY5hsvjy0pfMQhly9ZAyTMexIPl831AJPReVgApmJwYNSHymYq1pRO8HKTsqcUZAoiuphGW85auursfwAZDZD&method=get&qpl_active_flow_ids=270213183&qpl_active_flow_instance_ids=270213183_b7f2a4eaf93b38d76&__cppo=1', httr::add_headers(.headers=headers), body = data)




create_targeting_spec <- function(age_max =55){
  
  facebook_stuff <- '
  "publisher_platforms": [
    "facebook",
    "instagram",
    "audience_network",
    "messenger"
  ],
  "facebook_positions": [
    "feed",
    "instant_article",
    "instream_video",
    "right_hand_column",
    "video_feeds",
    "marketplace",
    "story",
    "facebook_reels_overlay",
    "search",
    "groups_feed"
  ],
  "instagram_positions": [
    "stream",
    "story",
    "explore",
    "reels",
    "shop"
  ],
  "messenger_positions": [
    "messenger_home",
    "story"
  ],
  "device_platforms": [
    "mobile",
    "desktop"
  ],
  "audience_network_positions": [
    "classic",
    "rewarded_video"
  ],
  "oculus_positions": [],
  "excluded_publisher_list_ids": [],
  "user_device": [],
  "excluded_user_device": [],
  "user_os": [],
  "wireless_carrier": [],
  "targeting_optimization": "none",
  "brand_safety_content_filter_levels": [
    "FACEBOOK_STANDARD",
    "AN_STANDARD"
  ],
  "excluded_brand_safety_content_types": []
  ' 
  # This will always stay the same to get comparable results
  
  facebook_stuff <- strwrap(facebook_stuff, width=10000, simplify=TRUE)
  
  countries <- c("ES","DE","FR")
  
  geo_locations_begin <- '
  "geo_locations": {
    "countries": ['
  
  geo_locations_end <-'],
    "location_types": [
      "home"
    ]
  }'
  countries_string <- paste0('"',countries,'"',  collapse=',')
  geo_locations_string <- paste0(geo_locations_begin,countries_string,geo_locations_end)
  geo_locations_string
  age_min <- 18
  age_string <- paste0('"age_min":',age_min,'"age_max":',age_max)
  
  other_stuff <-'"flexible_spec": [
    {
      "life_events": [
        {
          "id": "6003053984972",
          "name": "Long-distance relationship"
        }
      ]
    }
  ]'
  
  
  targeting_spec = paste0("{",geo_locations_string,",",facebook_stuff,",",age_string,",",other_stuff,"}")
  targeting_spec <- strwrap(targeting_spec, width=20000, simplify=TRUE)
  
  return(targeting_spec)
}
